### ISSUE TITLE
Getting Error message while patching game.

### ISSUE THREAD

**Issue by ChrisMiliW** [GovanifY/KH2FM_Toolkit#4]
When I'm patching the game using the toolkit I get this message in red text, in which I'm assuming is the end of patching. I get the option to continue anyways and when I do and try to boot the game I get stuck on the screen. I was wondering what the issue is and how to fix it.

 Error creating IDX/IMG: adjusted(length) <= 0
Parameter name: length
   at GovanifY.Utility.Substream..ctor(Stream baseStream, Int64 origin, Int64 length, Boolean leaveOpen)
   at IDX_Tools.IMGFile.GetFileStream(IDXEntry entry)
   at KH2FM_Toolkit.Program.PatchIDXInternal(Stream sidx, Stream simg, Stream timg, Int64 imgOffset, ConsoleProgress progress, UInt32 parenthash)
   at KH2FM_Toolkit.Program.PatchIDX(Stream idx, Stream img, FileDescriptor imgd, ISOCopyWriter niso, ConsoleProgress progress, Boolean IsOVL)
   at KH2FM_Toolkit.Program.PatchISO(Stream isofile, Stream nisofile)

**Comment by GovanifY** [comment]
Hey! I think you're trying to patch a bad ISO. The error you see happens here:

https://github.com/GovanifY/KH2FM_Toolkit/blob/80cb048ac71ded3fb470808714ed2f001bf556a9/Program.cs#L634-L647

What happens is that it tries to get a filestream to the original ISO IMG file, which ends up not being adjusted.

Can you please checkup the hash of your iso? You can do so by running `KH2FM_Toolkit -verifyiso my.iso`

**Comment by ChrisMiliW** [comment]
I ran  -verifyiso my.iso and got the same error as before what is the hash I'm looking for.

**Comment by GovanifY** [comment]
You have to run it in the command line.

Type `windows+r`, `cmd.exe` and then `KH2FM_Toolkit.exe -verifyiso my.iso`. Verify you are in the same folder as the one where the toolkit and your iso is.

**Comment by ChrisMiliW** [comment]
I figured out it was me. I just didn't have enough space to patch the game properly. I tried it on a different drive and it worked. Thank you for the support.

**Comment by GovanifY** [comment]
Huh, that's an interesting one. Probably could have guessed as the adjusted length was when writing a new IMG; I thought it was missing the check after the initial copy.

Glad it's resolved though, enjoy :)
